services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=order_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - .:/var/www/html:delegated
      - /var/www/html/vendor
      - /var/www/html/storage
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- php artisan key:generate --force && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: order_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
